
export const JSONS = [
    {
      name: "Manager DashBoard",
      icon: "images/sampleimage.svg",
      id: "b69b6343-dc95-408b-ab7d-96a0921ec1e9",
      router: "dashboard",
      nav_icon: "DashBoard",
      link: ["dashboard"],
      active_status: false,
      type: "menu",
      permission: {
        create: false,
        update: false,
        read: false,
        delete: false,
      },
    },
    {
        name: "Organization",
        icon: "images/sampleimage.svg",
        nav_icon: "Organization",
        id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
        router: null,
        link: [
          "companyMaster",
          "companyCreation",
          "editcompany",
          "jobs",
          "department",
        ],
        active_status: false,
        type: "menu",
        permission: {
          create: false,
          update: false,
          read: false,
          delete: false,
        },
        children: [
          {
            name: "Companies",
            icon: "images/document.svg",
            nav_icon: "Companies",
            id: "f59472eb-37ac-44c4-8055-11e776f08d58",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: "companyMaster",
            link: ["companyMaster", "companyCreation", "editcompany"],
            active_status: false,
            type: "menu",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
            children: [
              {
                name: "Companies1",
                icon: "images/document.svg",
                nav_icon: "Companies",
                id: "f59472eb-37ac-44c4-8055-11e776f081981",
                parent_id: "f59472eb-37ac-44c4-8055-11e776f08d58",
                router: "companyMaster",
                link: ["companyMaster", "companyCreation", "editcompany"],
                active_status: false,
                type: "menu",
                permission: {
                  create: false,
                  update: false,
                  read: false,
                  delete: false,
                },
              },
            ]
          },
          {
            name: "Companies Creation",
            icon: "images/document.svg",
            id: "e5d147d2-9cca-492e-8cb7-619dea5a928a",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: "companyCreation",
            active_status: false,
            type: "page",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
          },
          {
            name: "Companies Edit",
            icon: "images/document.svg",
            id: "aff42570-6582-4a17-99a9-bc14f23a1359",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: "editcompany",
            active_status: false,
            type: "page",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
          },
          {
            name: "Department",
            icon: "images/document.svg",
            nav_icon: "Department",
            id: "c49712c8-9204-4663-84ab-34bfaa55428e",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: "department",
            link: ["department"],
            active_status: false,
            type: "menu",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
          },
          {
            name: "Section",
            icon: "images/document.svg",
            nav_icon: "Section",
            id: "a91add24-361b-44c4-814b-2f6f320b9c15",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: null,
            link: [],
            active_status: false,
            type: "menu",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
          },
          {
            name: "Jobs",
            icon: "images/document.svg",
            nav_icon: "Jobs",
            id: "58647b45-6ca4-4fc2-a991-a401eb1d446e",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: "jobs",
            link: ["jobs"],
            active_status: false,
            type: "menu",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
          },
          {
            name: "Users",
            icon: "images/document.svg",
            nav_icon: "Users",
            id: "97939b1c-c0aa-43f7-9606-ba4f17169104",
            parent_id: "0b511ea6-5c06-4fdc-9123-e793c44088f6",
            router: null,
            link: [],
            active_status: false,
            type: "menu",
            permission: {
              create: false,
              update: false,
              read: false,
              delete: false,
            },
          },
        ],
      },
  ];
  